spring:
  application:
    name: ms-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bills-project
      client:
        registration:
          keycloak:
            client-id: bills-users-internal-feign
            client-secret: dOFKXdXECVocMCjLsoVmsoi8Riy5jn6d
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bills-project
bills:
  keycloak:
    realm: bills-project
    serverurl: http://localhost:8080/
    clientid: bills-users-internal-feign
    clientsecret: dOFKXdXECVocMCjLsoVmsoi8Riy5jn6d

server:
  port: 8084

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
